FROM python:3.10-slim

# Install system dependencies
RUN apt-get update && \
    apt-get install -y cmake build-essential libsm6 libxext6 libxrender-dev \
    libgtk-3-dev libboost-python-dev libopenblas-dev liblapack-dev python3-dev \
    libgl1 libglib2.0-0 gcc g++ wget make && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app

# Upgrade pip and install Python build dependencies
RUN python -m pip install --upgrade pip
RUN pip install wheel setuptools cmake numpy==1.24.3

# Install all requirements (including dlib)
RUN pip install -r requirements.txt

CMD ["gunicorn", "app:app"]