services:
  - type: web
    name: advanced-attendance-system
    env: python
    runtime: python3
    buildCommand: |
      apt-get update && apt-get install -y cmake build-essential libsm6 libxext6 libxrender-dev
      python3.10 -m venv venv
      . venv/bin/activate
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: PATH
        value: /opt/python/3.10.11/bin:$PATH
    autoscaling:
      minInstances: 1
      maxInstances: 1
    resources:
      memoryLimit: 2048Mi
