services:
  - type: web
    name: advanced-attendance-system
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: PATH
        value: /opt/python/3.10.11/bin:$PATH
    autoscaling:
      minInstances: 1
      maxInstances: 1
    resources:
      memoryLimit: 2048Mi
